SELECT id, compositor FROM musicas;
SELECT composicao, tempo FROM musicas WHERE tempo > 4*60;
SELECT compositor, composicao FROM musicas WHERE id BETWEEN 47 AND 123;
SELECT * FROM musicas WHERE compositor IS NOT NULL AND compositor <> 'Bach' AND tempo < 5*60;
SELECT composicao, tempo FROM musicas WHERE compositor = 'Mozart' OR compositor = 'Bach';
SELECT * FROM musicas ORDER BY id DESC;
SELECT * FROM musicas ORDER BY tempo DESC;
SELECT * FROM musicas ORDER BY tempo ASC LIMIT 5;
SELECT * FROM musicas ORDER BY tempo DESC LIMIT 10;
SELECT * FROM musicas ORDER BY tempo ASC LIMIT 10 OFFSET 5;
SELECT * FROM musicas LIMIT 10 OFFSET 10*3;
SELECT * FROM musicas LIMIT 12 OFFSET 12*5;
SELECT DISTINCT compositor FROM musicas WHERE compositor IS NOT NULL;
SELECT DISTINCT compositor, composicao FROM musicas;
SELECT * FROM musicas WHERE compositor LIKE 'Bra%';
SELECT * FROM musicas WHERE ritmo LIKE '%troppo';
SELECT * FROM musicas WHERE composicao ILIKE '%quartet%';
SELECT * FROM musicas WHERE composicao NOT ILIKE '%quintet%';